version: '3.0'
services:
  nodeamericocru:
    container_name: nrCRU
    build: ./services/nodered/.
    restart: unless-stopped
    user: "0"
    privileged: true
    env_file: ./services/hannathon-node/nodered.env
    ports:
    - 1880
    - 2080
    networks:
      default:
        ipv4_address: 172.19.0.36
        aliases:
          - americo_cru_nr
      backend:
        ipv4_address: 172.30.0.36
        aliases:
          - americo_cru_nr
    volumes:
      - ./volumes/nrCRU/data:/data
    environment:
      VIRTUAL_HOST: americo-CRU.scadadevs.com
      VIRTUAL_PORT: 1880
      LETSENCRYPT_HOST: americo-CRU.scadadevs.com
      LETSENCRYPT_EMAIL: twinflameautomation@gmail.com


      #  nodehannakrampf:
      #    container_name: nrKrampf
      #    build: ./services/nodered/.
      #    restart: unless-stopped
      #    user: "0"
      #    privileged: true
      #    env_file: ./services/hannathon-node/nodered.env
      #    ports:
      #    - 1880
      #    - 2080
      #    networks:
      #      default:
      #        ipv4_address: 172.19.0.59
      #        aliases:
      #          - hanna_Krampf_nr
      #      backend:
      #        ipv4_address: 172.30.0.59
      #        aliases:
      #          - hanna_krampf_nr
      #    volumes:
      #      - ./volumes/nrKrampf/data:/data
      #    environment:
      #      VIRTUAL_HOST: hannathon.krampf.scadadevs.com
      #      VIRTUAL_PORT: 1880
      #      LETSENCRYPT_HOST: hannathon.krampf.scadadevs.com
      #      LETSENCRYPT_EMAIL: twinflameautomation@gmail.com


  cruInflux:
    container_name: dbcru
    image: "influxdb:latest"
    restart: unless-stopped
    ports:
      - 8086
      - 8083
      - 2003
    env_file:
      - ./services/hannathon-db/influxdb.env
    volumes:
      - ./volumes/dbcru/data:/var/lib/influxdb
      - ./backups/dbcru/db:/var/lib/influxdb/backup
    networks:
      default:
        ipv4_address: 172.19.0.42
        aliases:
          - americo-cru_db
      backend:
        ipv4_address: 172.30.0.42
        aliases:
          - americo-cru_db

networks:
  default:
    external:
      name: nginx-proxy
  backend:
    external:
      name: container-comm 

