version: '3'
services:

  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: unless-stopped
    ports:
      - 9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/portainer/data:/data
    environment:
      VIRTUAL_HOST: portainer.scada-go.com
      VIRTUAL_PORT: 9000
      LETSENCRYPT_HOST: portainer.scada-go.com
      LETSENCRYPT_EMAIL: wally.hudnall@gmail.com
    networks:
      default:
        ipv4_address: 172.19.0.52
        aliases:
          - portainer
      backend:
        ipv4_address: 172.30.0.52
        aliases:
          - portainer


  nodered:
    container_name: nodered
    build: ./services/nodered/.
    restart: unless-stopped
    user: "0"
    privileged: true
    env_file: ./services/nodered/nodered.env
    ports:
      - 32865:1880
      - 1883
      - 2083
      - 8001
    volumes:
      - ./volumes/nodered/data:/data
    networks:
      default:
        ipv4_address: 172.19.0.50
        aliases:
          - healthmgr
      backend:
        ipv4_address: 172.30.0.50
        aliases:
          - healthmgr
    environment:
      VIRTUAL_HOST: mqtthealth.scadadevs.com
      VIRTUAL_PORT: 1880
      LETSENCRYPT_HOST: mqtthealth.scadadevs.com
      LETSENCRYPT_EMAIL: twinflameautomation@gmail.com

  influxdb:
    container_name: influxdb
    image: "influxdb:latest"
    restart: unless-stopped
    ports:
      - 8086
      - 8083
      - 2003
    env_file:
      - ./services/influxdb/influxdb.env
    volumes:
      - ./volumes/influxdb/data:/var/lib/influxdb
      - ./backups/influxdb/db:/var/lib/influxdb/backup
    networks:
      default:
        ipv4_address: 172.19.0.53
        aliases:
          - metricsdb
      backend:
        ipv4_address: 172.30.0.53
        aliases:
          - metricsdb


  influx_2:
    container_name: influxdb_2
    image: "influxdb:latest"
    restart: unless-stopped
    ports:
      - 8086
      - 8083
      - 2003
    env_file:
      - ./services/influx_2/influxdb.env
    volumes:
      - ./volumes/influx_2/data:/var/lib/influxdb
      - ./backups/influx_2/db:/var/lib/influxdb/backup
    networks:
      default:
        ipv4_address: 172.19.0.54
        aliases:
          - coviddb
      backend:
        ipv4_address: 172.30.0.54
        aliases:
          - coviddb



  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "0"
    ports:
      - 3000
    env_file:
      - ./services/grafana/grafana.env
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
      - ./volumes/grafana/log:/var/log/grafana
    environment:
      VIRTUAL_HOST: grafana.scada-go.com
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: grafana.scada-go.com
      LETSENCRYPT_EMAIL: wally.hudnall@gmail.com
    networks:
      default:
        ipv4_address: 172.19.0.55
        aliases:
          - grafana
      backend:
        ipv4_address: 172.30.0.55
        aliases:
          - grafana

      #  container_name: mosquitto
      # image: eclipse-mosquitto:latest
      # restart: unless-stopped
      #  user: "1883"
      # ports:
      #  - 1883
      #  - 9001
      # volumes:
      #  - ./volumes/mosquitto/data:/mosquitto/data
      #  - ./volumes/mosquitto/log:/mosquitto/log
      # - ./services/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  telegraf:
    container_name: telegraf
    image: telegraf
    volumes:
      - ./services/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
    networks:
      default:
        ipv4_address: 172.19.0.56
        aliases:
          - telegraf
      backend:
        ipv4_address: 172.30.0.56
        aliases:
          - telegraf


networks:
  default:
    external:
      name: nginx-proxy
  backend:
    external:
      name: container-comm
