  motioneye:
    image: "ccrisan/motioneye:master-armhf"
    container_name: "motioneye"
    restart: unless-stopped
    ports:
      - 8765:8765 
      - 8081:8081
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/motioneye/etc_motioneye:/etc/motioneye
      - ./volumes/motioneye/var_lib_motioneye:/var/lib/motioneye
    #devices:
    #  - "/dev/video0:/dev/video0"

