  homebridge:
    container_name: homebridge
    image: oznu/homebridge:no-avahi-arm32v6
    restart: unless-stopped
    network_mode: host
    env_file: ./services/homebridge/homebridge.env
    volumes:
      - ./volumes/homebridge:/homebridge
