  influxdb_2:
    container_name: influxdb_2
    image: "influxdb:latest"
    restart: unless-stopped
    ports:
      - 8086:8086
      - 8083:8083
      - 2003:2003
    env_file:
      - ./services/influxdb_2/influxdb.env
    volumes:
      - ./volumes/influxdb_2/data:/var/lib/influxdb
      - ./backups/influxdb_2/db:/var/lib/influxdb/backup
