

version: "2.1"
services:
  ldap-auth:
    image: linuxserver/ldap-auth
    container_name: ldap-auth
    environment:
      - TZ=America/Chicago
    ports:
      - 8888
      - 9000
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.19.0.65
      backend:
        ipv4_address: 172.30.0.65

networks:
  default:
    external:
      name: nginx-proxy
  backend:
    external:
      name: container-comm
